name: delpoy to AWS

#trigger
on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "14"
